library(readxl)
library(CytoMethIC)
library(sesame)
sesameDataCache()
library(BiocParallel)
library(dplyr)
library(Rtsne)
library(ggplot2)
library(viridis)
library(parallel)
library(BiocParallel)
library(writexl)

meta1 = read_excel("/home/xuh6/scr1_xuh6/projects/PMBB_data_analysis/20241213_PMBB_MASTER.xlsx")
betas = openSesame(sprintf("/mnt/isilon/zhou_lab/projects/20230125_nonGEO_IDATs/MSA/%s", meta1$IDAT), BPPARAM=BiocParallel::MulticoreParam(20))

betasHM450 = mLiftOver(betas, "HM450", BPPARAM=BiocParallel::MulticoreParam(20))
saveRDS(betasHM450, file="20241220_betasHM450.rds")
betasHM450_imputed = imputeBetas(betasHM450)
colnames(betasHM450_imputed) <- colnames(betasHM450)
saveRDS(betasHM450_imputed, file="20241220_betasHM450_imputed.rds")
